### ISSUE TITLE
while starting server in the example

### ISSUE THREAD

**Issue by apurva165** [zemuldo/iso_8583#48]
getting error while starting server "npm run t"  

Error: Cannot find module 'jxon'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\akulkarni\Documents\iso_8583-master\lib\8583.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

tried re installing packages still not working

**Comment by zemuldo** [comment]
Try navigating to the root of the example and delete `node_modules` directory then run `npm install`

**Comment by zemuldo** [comment]
In the projects root run, `npm install`. then navigate to the example dir and try again.
